[package]
name = "papyrus"
version = "0.1.0"
authors = ["Ot√°vio Pace <otaviopp8@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
structopt = "0.3"
rust-crypto = "^0.2"
flate2 = "1.0"
